#!/usr/bin/env bash
set -euo pipefail

# Show_IP.sh
# Quickly display IP and routing information for the host
# Author: Yash Patil
# Usage: Show_IP.sh [-s] [-v]
#   -s  Summary (default): concise overview
#   -v  Verbose: include full output of supporting commands

SUMMARY=1
VERBOSE=0
for arg in "$@"; do
  case "$arg" in
    -v|--verbose) SUMMARY=0; VERBOSE=1 ;;
    -s|--summary) SUMMARY=1 ;;
    -h|--help) echo "Usage: $0 [-s|--summary] [-v|--verbose]"; exit 0 ;;
    *) echo "Unknown arg: $arg"; echo "Usage: $0 [-s|--summary] [-v|--verbose]"; exit 1 ;;
  esac
done

echo "Show IP information - generated by Show_IP.sh"
echo "Author: Yash Patil"
echo "Host: $(hostname -f 2>/dev/null || hostname)"
echo

# Helper to run command if available
run_if() {
  if command -v "$1" >/dev/null 2>&1; then
    shift
    echo "--- $* ---"
    "$@"
    echo
  fi
}

# Summary output
if [[ $SUMMARY -eq 1 ]]; then
  echo "Interfaces (brief):"
  if command -v ip >/dev/null 2>&1; then
    ip -brief address show
  else
    if command -v ifconfig >/dev/null 2>&1; then
      ifconfig -a | sed -n '1,200p'
    fi
  fi
  echo

  echo "Default route(s):"
  if command -v ip >/dev/null 2>&1; then
    ip route show default || true
  else
    netstat -rn | awk '/^0.0.0.0|^default/ {print}' || true
  fi
  echo

  echo "Nameservers:"
  awk '/^nameserver/ {print $2}' /etc/resolv.conf 2>/dev/null || echo "(none)"
  echo

  echo "Neighbor/ARP (short):"
  if command -v ip >/dev/null 2>&1; then
    ip neigh show
  else
    arp -n || true
  fi
  echo

  echo "Active listening sockets (short):"
  if command -v ss >/dev/null 2>&1; then
    ss -tuln | sed -n '1,200p'
  elif command -v netstat >/dev/null 2>&1; then
    netstat -tuln | sed -n '1,200p'
  fi
  echo

  if [[ $VERBOSE -eq 1 ]]; then
    echo "(Now showing verbose details below)"
  else
    echo "Run with -v for full details."
    exit 0
  fi
fi

# Verbose / full details
run_if ip ip -d link show
run_if ip ip -d addr show
run_if ip ip -s link
run_if ip ip route show
run_if ip ip -6 route show || true
run_if ip ip rule show || true
run_if ip ip neigh show
run_if nmcli nmcli device status
run_if nmcli nmcli connection show
run_if systemctl systemctl status systemd-networkd --no-pager || true
run_if systemctl systemctl status NetworkManager --no-pager || true
run_if ss ss -tunap || true
run_if lsof lsof -i -P -n | head -n 200 || true
run_if ethtool ethtool --help >/dev/null 2>&1 && echo "ethtool available (run ethtool <iface> for details)" || true

exit 0
